version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3050:3050"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurant
    ports:
      - "4406:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql